##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: NC Banned Books Collection 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Let Freedom Read
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This collection provides its users with a comprehensive compilation of banned books to peruse and utilize. The main focus is facilitating access to various books which have been banned throughout K-12 education in several US states during recent years. The primary user group which the collection is designed for is K-12 students in school districts that have been heavily affected by the book bannings. However, the collection is also very much intended to be a teachers’ resource for education in the broad range of Diversity Equity Inclusion (DEI) courses that would otherwise be immensely impeded by a lack of affordable access to these reading materials. Furthermore, the collection is meant to raise wider public awareness regarding the wide array of DEI-related books which currently face access barriers brought on by CRT-hysteria and other cultural panic book banning legislation over the past few years. Depending on the state, book bans numbering into hundreds of authors and titles have severely diminished the wealth of DEI curricular and extracurricular public-funded reading students have the Constitutional right to engage with according to the 1st Amendment. This collection will help ensure such book bans do not impede K-12 students’ affordable access to the broad spectrum of books which might interest them, regardless of what legislation is being enacted in their local school district."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Various authors

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: nc-bannedbooks

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "G-123XXXXXX"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
